global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#mikhail_bakaev'
