{
 "title": "Docker_daemon_monitoring",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# containers per state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    {
     "format": "short",
     "label": "Number of containers in a given state"
    }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"docker\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage - RSS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"docker\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Container Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Create",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(engine_daemon_container_actions_seconds_bucket{action=\"create\"}[1m])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Start",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(engine_daemon_container_actions_seconds_bucket{action=\"start\"}[1m])",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}